name: macOS Builds

on:
  push:
    branches:
      - "macOS"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:

jobs:

  
  build-macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          modules: "qtcharts"

      - name: Install dependencies
        run: |
          brew install boost clang

      - name: Clone bmorecoin
        run: |
          rm -rf cryptonote
          git clone https://github.com/BMoreToken/bmorecoin.git cryptonote

      - name: Build
        id: build
        run: |
          build_folder="build/release"
          ccx_version=${GITHUB_SHA::7}
          release_name="ccx-desktop-macOS-dev-$ccx_version"
          app_name="bmorecoin.app"

          make -j3 build-release
          cd "$build_folder"
          macdeployqt "$app_name"
          cpack
          mkdir "$release_name"
          mv *.dmg "$release_name".dmg
          mv "$release_name".dmg "$release_name"

          echo "::set-output name=release_name::${release_name}"
          echo "::set-output name=artifact_path::$build_folder/$release_name"

      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.build.outputs.release_name }}
          path: ${{ steps.build.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
