name: macOS Nightly

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*" # We don't want this to run on release
  pull_request:
  
jobs:
  build-macos11:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@master

      - name: Prepare version
        id: setup
        run: |
          os=macos-11
          ccx_version=${GITHUB_SHA::7}
          release_name=ccx-cli-"$os"-dev-"$ccx_version"
          echo "::set-output name=release_name::${release_name}"
      - name: Install dependencies
        run: |
          brew install boost
      - name: Build
        id: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DSTATIC=ON
          make -j2
      - name: Prepare release
        run: |
          mkdir build/bin
          mv build/src/conceald build/bin
          mv build/src/concealwallet build/bin
          mv build/src/optimizer build/bin
          mv build/src/walletd build/bin
          mv build/tests/*_tests build/bin
      - name: Upload To GH Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.setup.outputs.release_name }}
          path: build/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: core_tests
        run: |
          cd build/bin
          ./core_tests --generate_and_play_test_data
      - name: difficulty_tests
        run: |
          cp tests/Difficulty/data.txt build/bin
          cd build/bin
          ./difficulty_tests data.txt
      - name: performance_tests
        run: |
          cd build/bin
          ./performance_tests
